### PR TITLE
6.x Support

### PR DESCRIPTION
**Pull request by jadestorm**
#### Pull Request (PR) description
This PR adds support for the 6.x series of winlogbeat.  Mostly, that involves some config differences and the ability to adapt to a 6.* version.  6.x deprecated the -configtest option in lieu of a new "test config" which is basically the same thing (but you don't have to specify -N).  I do not believe the real_version check is actually working through, but as long as you specify major_version as '6', you should be good to go.  In other words it's not perfect.  ;)

Quick example call:
```
class { '::winlogbeat':
  package_ensure => '6.2.3',
  major_version  => '6',
}
```

#### This Pull Request (PR) fixes the following issues
n/a

### CODE REVIEW

**Comment by jadestorm** [comment]
Hold tight on even potentially accepting this atm.  I'm running into some bizarre behavior on some of my hosts that I'd like to track down first.  That said I'm certainly open to comments and if you need me to do anything extra for this PR let me know.

**Comment by jadestorm** [comment]
So, I think that this patch adds 6.x support "just fine" <tm>.  However, I am having trouble with the unzip step completely atm on quite a few of my machines -- tried running the command by hand and it appears some component is missing.  Forums seem to indicate it might be .net 4.5 that's required.  I don't entirely understand the comment in the code about 7zip being required for the archive module though.  Anyway, I'm going to leave this PR "as is" and fork and mess around with maybe just switching to a raw archive solution instead of the extra steps.

**Comment by jadestorm** [comment]
Nevermind re: 7zip, I hadn't noticed that the archive module actually requires 7zip.  Either way, it appears that the commands used to install are not functioning under Windows Server 2016.  I came across a discussion that indicated that it requires .Net 4.5 ---  either way I went a different route which was to build an -optional- process of choosing chocolatey.  So from my testing atm -- this patch is good to go for adding 6.x support.  I may submit a second patch that allows folk to enable chocolatey support but default to your implementation.  =)

**Comment by jacobmw** [comment]
Is there any reason not to merge this in?  We would very much like to have this support.

**Comment by ghoneycutt** [comment]
This functionality has been added. Thank you!

The template plate does not exist. Please feel free to re-open/rebase.

**Pull request closed without merging**
